#! /bin/bash

# mondays
date[2]='11/12/2012'   # week 2
date[3]='11/19/2012'   # week 3
date[4]='11/26/2012'   # week 4
date[5]='12/03/2012'  # week 5
date[6]='12/10/2012'  # week 6
date[7]='12/17/2012'  # week 7
date[8]='12/24/2012'  # week 8
date[9]='12/31/2012'  # week 9
date[10]='01/07/2013'  # week 10
date[11]='01/14/2013'  # week 11
date[12]='01/21/2013'  # week 12
date[13]='01/28/2013'  # week 13
date[14]='02/04/2013'  # week 14
date[15]='02/11/2013'  # week 15
date[16]='02/18/2013'  # week 16
date[17]='02/25/2013'  # week 17
date[18]='03/04/2013'  # week 18
date[19]='03/11/2013'  # week 19  
date[20]='03/18/2013'  # week 20 - AP Final, Coaches Final
date[21]='03/25/2013'  # week 21 - Coaches Postseason
date[22]='04/01/2013'  # week 22
date[23]='04/08/2013'  # week 23
date[24]='04/15/2013'  # week 24

url='http://www.teamrankings.com/ajax/league/v3/rankings_controller.php'

param='type=detail&league=ncb&rating_id=514&season_id=311&cat_type=2&view=team_v2&view_type=team&table_view=team_v2&force_period_id=&is_rpi_ranking=1&date='

echo "${#date[@]}"

for ((i=2; i<=${#date[@]} + 1; i++)); do
  ENCODEDDATE=$(php -r "echo urlencode(\"${date[i]}\");")
  content=`curl --data $param$ENCODEDDATE $url`
  echo "$content" > ${date[i]:6:4}-${date[i]:0:2}-${date[i]:3:2}.html
done

# notes
# there is no preseason RPI rating, so ratings begin on what we're 
# calling week 2 (2012-11-12)
